# Generated by Django 4.2.16 on 2025-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Country name')),
                ('cod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country cod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Document Type Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Type Description')),
                ('type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Document Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('person_type', models.CharField(choices=[('N', 'Natural'), ('L', 'Legal')], default='L', max_length=2, verbose_name='Person Type')),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trade Name')),
                ('federal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Federal Tax Id')),
                ('state_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='State Tax Id')),
                ('ssn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Social Security Number')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('number', models.CharField(max_length=30, verbose_name='Document Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=60, verbose_name='Partner Type Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=30, verbose_name='Document Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=30, verbose_name='Document Number')),
                ('number', models.CharField(max_length=30, verbose_name='Document Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
