# Generated by Django 4.2.16 on 2025-04-02 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonemask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonemask',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='phonemask',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='phonemask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.documenttype', verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.ManyToManyField(blank=True, to='partners.partnertype', verbose_name='Partner Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
